mozilla/solitude

requirements/docs.txt
Bump docs reqs to match webpay. This may stop some of the build errors from rtd.
=> Bump docs reqs

bin/docker/supervisor.conf, lib/boku/client.py, lib/boku/errors.py, lib/boku/forms.py, lib/boku/tests/test_client.py, lib/boku/tests/test_forms.py, lib/provider/boku.py, lib/provider/tests/test_boku.py, lib/proxy/tests.py, lib/proxy/urls.py, lib/proxy/views.py, solitude/settings/test.py
Sorry for the noise, you've seen most of this. It got simple, then complicated, then too complicated and then I removed most of that and got back to simple. Kinda embarrasing how long that took.
Here's a test in docker with an invalid signature:
```
...
* HTTP 1.0, assume close after body
< HTTP/1.0 400 BAD REQUEST
< Server: WSGIServer/0.1 Python/2.7.5
< Content-Length: 34
< Vary: Accept
< ETag: "14103897df789f29e185eb62f645a0dc"
< Allow: POST, OPTIONS
< Date: Tue, 03 Mar 2015 23:44:02 GMT
< Content-Type: application/json
< 
* Closing connection #0
{"sig": ["Not a valid signature"]
```
A valid signature goes on to then verify the transaction "foo" which it then fails with amusingly enough.
=> add in md5 sig check (bug 1130213)

lib/bango/forms.py, lib/bango/resources/billing.py, lib/bango/resources/cached.py, lib/bango/signals.py
Follow up to removing the implicit transaction, we no longer need the create signal and some of the data passed through to the form.
=> remove create signal as well (bug 1036579)

docs/topics/generic.rst, lib/bango/forms.py, lib/transactions/constants.py, lib/transactions/forms.py, lib/transactions/models.py, lib/transactions/resources.py, lib/transactions/tests/test_api.py, lib/transactions/tests/test_forms.py, lib/transactions/tests/test_models.py, migrations/51-make-provider-optional.sql, migrations/52-add-error-reason.sql
* allows a transaction to have no provider, so we can report transaction failures when there is no error
* adds in two new states
* makes ERRORED and end state, that you cannot update from
=> allow transactions to be created and errored before provider is known (bug 1140615)

Dockerfile, docs/conf.py, docs/topics/braintree.rst, docs/topics/setup.rst, requirements/docs.txt
Also:
- install docs modules in docker image
- show the RTD theme when building docs locally
=> Link to braintree settings in docs

lib/bango/forms.py, lib/bango/tests/samples.py
Example from today:
```
May 21 20:49:52 localhost6.localdomain: [10.8.83.211] w.bango:DEBUG Bango notice: '\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?>...<item name="externalCPTransID" value="webpay:...
```
=> looks like the externalCPTransID changed

.travis.yml, requirements/prod.txt
* the old version of django-extensions was causing a failure in schematic migrations, which was breaking solitude start up
=> bump django-extensions

lib/bango/forms.py, lib/brains/__init__.py, lib/brains/tests/test_webhook.py, lib/brains/views/webhook.py, lib/brains/webhooks.py
this is the newly modeled event based on mozilla/payments#28 which does not require a transaction to be made in payments-service
=> process a subscription charged event

lib/brains/management/commands/braintree_webhook.py, lib/brains/management/commands/samples/webhooks.py, lib/brains/tests/test_webhook.py, lib/brains/webhooks.py
* fixes #430 
* in management command, allows the transaction to be specified in, otherwise creates a new one
* send unsuccessful in the management command
=> add in unsuccessfully charged webhook

docs/topics/braintree.rst, lib/brains/management/commands/braintree_webhook.py, lib/brains/management/commands/samples/webhooks.py, lib/brains/serializers.py, lib/brains/tests/test_webhook.py, lib/brains/webhooks.py
* update the braintree_config command to make subscription_canceled possible
* fix the spelling of subscription_canceled in the code (bah!)
* fixes #484 
* cope with the fact that there may not be transactions in the response (see #462)
* save the subscription onto the Process object to stop it being passed around
=> cope with subscription cancelled

.travis.yml, requirements/compiled.txt, requirements/dev.txt, requirements/prod.txt
There are 3 (sigh) entry points into building this:
* the fabfile for prod, which calls prod.txt (so M2Crypto is built already)
* the Dockerfile which calls test.txt > dev.txt > prod.txt and docs.txt (so it skips compiled and M2Crypto is built already)
* the .travis.yml file which calls test.txt > dev.txt > prod.txt and compiled.txt (so it pulls M2Crypto from wheelhouse)
=> upgrade m2crypto and remove sudo

lib/brains/forms.py, lib/brains/tests/test_forms.py, lib/brains/tests/test_paymethod.py, lib/brains/views/paymethod.py
* calls delete upon changing status to active
* if this happens multiple times it doesn't fail
* fixes #492 and supports mozilla/payments#84
* also prevents enabling a deactivated payment method which fixes #494
=> delete payment methods from braintree

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/tests/test_paymethod.py, lib/brains/urls.py, lib/brains/views/paymethod.py
* proposed change to paymethod cancelling, just an explicit end point
* seperates braintree and mozillay
Now to cancel:
```
curl --dump-header - -H "Content-Type: application/json" -X POST --data '{"paymethod": "/braintree/mozilla/paymethod/1/"} http://solitude:2602/braintree/paymethod/cancel/
```
* this would mean removing the ability to patch /braintree/paymethod/1/ from the bodyguard and changing to this.
=> improved pay method

lib/brains/tests/test_webhook.py, lib/brains/webhooks.py, solitude/tests/test.py, solitude/utils.py
* currently 40000 so it will look like this, up to...
```
In [4]: shorter(40000)
Out[4]: 'nUs'
In [5]: shorter(4000000000000)
Out[5]: 'ctRdH6eJ'
```
=> shorter transaction id based on the pk

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/tests/test_subscription.py, lib/brains/urls.py, lib/brains/views/subscription.py
* won't allow you to use an inactive subscription or paymethod
```
curl --dump-header - -H "Content-Type: application/json" -X POST --data '{"subscription": "/braintree/mozilla/subscription/2/", "paymethod": "/braintree/mozilla/paymethod/1/"}' http://solitude:2602/braintree/subscription/change/
```
=> change a subscriptions paymethod

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/tests/test_subscription.py, lib/brains/urls.py, lib/brains/views/subscription.py
* won't allow a subscription to be reactivated
* cancels the subscription in braintree
```
curl --dump-header - -H "Content-Type: application/json" -X POST --data '{"subscription": "/braintree/mozilla/subscription/1/"} http://solitude:2602/braintree/subscription/cancel/
```
=> Cancel subscription

lib/provider/client.py, lib/provider/tests/test_reference.py, lib/provider/tests/test_views.py, lib/provider/views.py, solitude/settings/base.py
* i was passing through to the auth that the final destination of zippy... was solitude-auth, that's silly the final URL for zippy requests is zippy, that's what the header is for
* let's move the final url calculation into the proxy, that's what the current lib/proxy does and makes this code easier
* let's set the default url to be the docker one, not paas
=> pass the right URL

docs/topics/braintree.rst, lib/brains/tests/test_paymethod.py, lib/brains/views/paymethod.py
The braintree result does not contain the payment_method definition.
=> Fix return result of pay method deletion

bin/docker/supervisor.conf, lib/provider/tests/test_views.py, solitude/settings/base.py
* things go through solitude-auth now, so remove the second process inside the solitude container
* set the default in settings to solitude-auth for docker to save another env variable
* fixes #515
=> no need for solitude proxy any more

solitude/settings/sites/prod/proxy.py
From Bug 1191932:
Greetings,
We'd like to set the SITE_URL as a variable for payments-proxy.  I've created a PR here, which seems like a small change, but wanted to verify with the dev team that this would not impact anything else.
The current SITE_URL for prod is set to https://payments-proxy.firefox.com, where we would want to configure that to https://payments-proxy.prod.mozaws.net as a variable instead of a static entry.
Thanks!
=> Set SITE URL as a variable for the payments-proxy

solitude/exceptions.py, solitude/settings/sites/dev/db.py, solitude/settings/sites/paymentsalt/db.py, solitude/settings/sites/prod/db.py, solitude/settings/sites/stage/db.py
* fixes #520 
* log before we attempt the roll back
* `DATABASES['default']` is being overridden, meaning we weren't in an atomic block although the code assumed that
=> turn on atomic requests on prod

lib/transactions/models.py, lib/transactions/tests/test_api.py, solitude/base.py, solitude/filter.py, solitude/tests/test.py
* fixes #523 
* pass on the ordering on the model down to django-filter, kinda confused why DRF doesn't do this already
* can't think of anything that explicitly relies on ordering in solitude, so should be ok
fyi @muffinresearch, this will ensure payment methods are ordered newest first
=> fix the ordering

docs/topics/generic.rst, lib/buyers/tests/test_api.py, lib/buyers/urls.py, lib/buyers/views.py
* hook up model method into the API
* `/generic/buyer/id/close/` is a nice URL, but kinda awkward to put together in payments-service, maybe? if you want a different URL kumar let me know.
* doesn't return anything about the closing... dunno if you want anything
* fixes #497
=> close account api

migrations/60-fix-subscription.sql
This column was changed accidentally in
https://github.com/mozilla/solitude/pull/535
=> Fix subscription_id in braintree_transaction table

lib/brains/tests/test_sale.py, lib/brains/views/sale.py, lib/brains/webhooks.py, lib/transactions/models.py, lib/transactions/tests/test_models.py
* fixes #541 
* moves the shorter id creation into the model to make it easier
* adds regression test and a bit of logging just for fun
=> create a transaction uuid for a sale

docs/topics/braintree.rst, docs/topics/generic.rst, lib/buyers/models.py, lib/buyers/serializers.py, lib/buyers/tests/test_api.py, migrations/62-authenticated-buyer.sql
Fixes https://github.com/mozilla/solitude/issues/545
This should allow us to create an email-only buyer (in services) before creating a recurring donation. Well, it was always possible to create an email-only buyer but this new flag will allow us to put restrictions elsewhere in Solitude if needed.
=> Mark buyers as authenticated or not (fixes #545)

lib/buyers/field.py, lib/buyers/tests/test_models.py
moves the check into `get_prep_value` which only occurs on de-serialization, not serialization, with a test to prove it
=> move prefix check
