docs/topics/boku.rst, lib/boku/client.py, lib/boku/forms.py, lib/boku/tests/test_client.py, lib/boku/tests/utils.py
=> Pass product name to Boku buy flow (bug 1008419)

Dockerfile, bin/docker/supervisor.conf
* we only need to expose 2602, not the proxy
* move the environment variables to be per solitude instance, so inside supervisor.conf, not the dockerfile
=> run solitude as a proxy (bug 1112672)

lib/bango/tests/test_resources.py, lib/transactions/models.py, solitude/base.py, solitude/tests/test.py
See also: https://github.com/mozilla/webpay/pull/615
=> move implicit bango transaction creation (bug 1036579)

solitude/settings/sites/altdev/db.py, solitude/settings/sites/altdev/proxy.py, solitude/settings/sites/dev/db.py, solitude/settings/sites/dev/proxy.py, solitude/settings/sites/paymentsalt/db.py, solitude/settings/sites/paymentsalt/proxy.py, solitude/settings/sites/prod/db.py, solitude/settings/sites/prod/proxy.py, solitude/settings/sites/stage/db.py, solitude/settings/sites/stage/proxy.py
=> Remove PAYPAL related settings from sites settings (bug 1147428)

.travis.yml, docs/topics/setup.rst, lib/brains/management/commands/braintree_config.py, lib/brains/tests/test_management.py, lib/brains/tests/test_token.py, solitude/authentication.py, solitude/settings/base.py, solitude/settings/test.py, solitude/tests/live.py, solitude/tests/test_authentication.py
Also fixes 403 handling, which was previously throwing a 500 error, not a 403.
Secrets are not available on pull requests, so the live tests will fail until we merge this.
=> live tests with some oauth action

docs/index.rst, docs/topics/overall.rst, docs/topics/setup.rst
=> document overall API details. Fixes #379

.curling, lib/provider/tests/test_reference.py, lib/provider/tests/test_views.py, lib/provider/views.py, lib/proxy/tests.py, requirements/prod.txt, solitude/settings/base.py, solitude/utils.py
=> upgrade curling and allow curling from the docker container to work

docs/topics/braintree.rst, lib/brains/serializers.py
=> add in some docs on the braintree buyer object

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/models.py, lib/brains/serializers.py, lib/brains/tests/base.py, lib/brains/tests/test_base.py, lib/brains/tests/test_buyer.py, lib/brains/tests/test_paymethod.py, lib/brains/urls.py, lib/brains/views/buyer.py, lib/brains/views/customer.py, lib/brains/views/paymethod.py, migrations/55-add-payment-method.sql, solitude/constants.py, solitude/exceptions.py
=> create a payment method api and model

lib/brains/tests/test_paymethod.py, lib/sellers/views.py, solitude/exceptions.py, solitude/filter.py, solitude/settings/base.py, solitude/settings/test.py, solitude/tests/test.py
=> a meaner django filter

docs/topics/braintree.rst, docs/topics/generic.rst, lib/brains/forms.py, lib/brains/models.py, lib/brains/serializers.py, lib/brains/tests/base.py, lib/brains/tests/test_subscription.py, lib/brains/urls.py, lib/brains/views/subscription.py, migrations/56-add-subscriptions.sql, solitude/related_fields.py
Requires https://github.com/mozilla/solitude/pull/392. Fixes mozilla/payments#18.
=> create a subscription method

lib/bango/tests/test_resources.py, lib/bango/views/status.py, lib/brains/tests/test_customer.py, lib/brains/tests/test_paymethod.py, lib/brains/tests/test_subscription.py, lib/transactions/management/commands/log.py, requirements/prod.txt, solitude/exceptions.py, solitude/settings/base.py, solitude/tests/test_error.py
already got an r? from kumar on this in previous pull request, but closed it rather than merge
=> upgrade django

docs/topics/overall.rst, lib/bango/tests/test_resources.py, lib/brains/errors.py, lib/brains/forms.py, lib/brains/tests/base.py, lib/brains/tests/test_base.py, lib/brains/tests/test_customer.py, lib/brains/tests/test_paymethod.py, lib/brains/tests/test_subscription.py, lib/brains/views/customer.py, lib/brains/views/paymethod.py, lib/brains/views/subscription.py, lib/buyers/forms.py, lib/buyers/serializers.py, lib/buyers/tests/test_api.py, lib/buyers/views.py, solitude/base.py, solitude/errors.py, solitude/exceptions.py, solitude/filter.py, solitude/settings/test.py, solitude/tests/test.py, solitude/tests/test_error.py
helps #349, but #416 and #417 are both needed to complete this
=> start of formatting errors more consistently

lib/brains/forms.py, lib/brains/tests/test_subscription.py
=> move name to descriptor

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/tests/test_webhook.py, lib/brains/urls.py, lib/brains/views/webhook.py
fixes mozilla/payments-service#16
=> add in a webhook handler

Dockerfile
helps fix #425, most of the rest of the fixes are in the base container
=> chop over 200mb off the Docker container

lib/brains/views/webhook.py, solitude/settings/base.py
=> more logging

bin/docker/supervisor.conf, lib/brains/client.py, lib/brains/management/commands/braintree_config.py, solitude/settings/base.py
=> make braintree use solitude-auth

lib/brains/client.py, lib/brains/forms.py, lib/brains/tests/base.py, lib/brains/tests/test_forms.py, lib/brains/tests/test_webhook.py, lib/brains/views/webhook.py
fixes #452 along with mozilla/solitude-auth#4
=> pass verification onto solitude-auth

lib/brains/client.py, lib/brains/forms.py, lib/brains/management/commands/braintree_config.py, lib/brains/tests/base.py, lib/brains/tests/test_client.py, lib/brains/tests/test_subscription.py, solitude/settings/test.py
* also throw an error if the BRAINTREE_PROXY isn't defined
=> flip external_id and public_id around

bin/docker/supervisor.conf
depends on https://github.com/mozilla/payments-env/pull/29
=> No need for proxy env, it's in docker

lib/brains/tests/test_webhook.py, lib/brains/webhooks.py, solitude/settings/base.py
* instead of looking at just the first one, look at them all
* ignore repeats
* save others with some info
* fixes #429
=> look at all the transactions on a webhook

lib/brains/tests/test_webhook.py, lib/brains/webhooks.py
this is branched off of https://github.com/mozilla/solitude/pull/465, look at that first
fixes #462
=> Cancelled transactions

docs/topics/braintree.rst, docs/topics/generic.rst, lib/brains/serializers.py, lib/brains/tests/test_subscription.py, lib/brains/tests/test_webhook.py, lib/brains/views/webhook.py, lib/brains/webhooks.py, solitude/settings/base.py
looking for feedback, concerned about the link between transactions and subscription, as mentioned in the comments
=> return something on webhooks

docs/topics/braintree.rst, lib/brains/models.py, lib/brains/serializers.py, lib/brains/tests/base.py, lib/brains/tests/test_base.py, lib/brains/tests/test_transaction.py, lib/brains/tests/test_webhook.py, lib/brains/urls.py, lib/brains/views/customer.py, lib/brains/views/paymethod.py, lib/brains/views/subscription.py, lib/brains/views/transaction.py, lib/brains/webhooks.py, migrations/57-add-braintree-transaction.sql
* fixes mozilla/payments#74 
* makes the Namespaced object simpler and a bit more flexible
* add in braintree transaction endpoint
* catch the submitted for settlement webhook as well
* requires #472, so maybe read that first
=> add in braintree transaction

docs/topics/braintree.rst, lib/brains/serializers.py, lib/brains/tests/test_webhook.py
* add in the buyer object into the result so that the service can get the email
=> return the buyer

docs/topics/braintree.rst, lib/brains/tests/test_subscription.py, lib/brains/views/subscription.py
=> allow lookup by provider_id

lib/brains/management/commands/braintree_config.py, requirements/prod.txt, solitude/settings/base.py
* fixes #454 
* makes external_id and public_id the same, don't think that affects anything, that's a webpay thing
=> use payments config

lib/brains/management/commands/braintree_webhook.py, lib/brains/management/commands/samples/webhooks.py
=> fake webhooks

.travis.yml, lib/brains/views/buyer.py, lib/brains/views/paymethod.py, lib/brains/views/subscription.py, lib/brains/views/transaction.py, solitude/base.py
* note moving the flake8 to `after_script` since I'm hoping it will allow us to see failed tests and then failed pep8 stuff
=> add in a simple view set, fixes #473

docs/topics/braintree.rst, lib/brains/serializers.py, lib/brains/tests/base.py, lib/brains/tests/test_webhook.py, solitude/base.py
* ..and I'm finding I keep doing print_as_json to generate docs and this saves me a few lines
* fixes #481
=> add in the product

Dockerfile, requirements/prod.txt
....also note that requirements/docs.txt has multiple conflicts with prod.txt and won't work on newer versions of pip. So removing that until someone fixes it up.
=> move to latest version of marketplace docker build

lib/brains/forms.py, lib/brains/models.py, lib/brains/tests/base.py, lib/brains/tests/test_models.py, lib/brains/views/paymethod.py, lib/brains/views/subscription.py, lib/buyers/models.py, lib/buyers/tests/test_models.py
* will close the issue when the API is accessible and documented from a HTTP request
* just the internal stuff for the moment
=> provide a close buyer method on the model

bin/docker/supervisor.conf, lib/provider/tests/test_views.py, lib/provider/views.py
=> pass through the correct header

docs/topics/braintree.rst, lib/brains/tests/test_transaction.py, lib/brains/views/transaction.py
Supports https://github.com/mozilla/payments-ui/issues/279
=> Filter transactions by user

bin/docker_run.sh
* this is pretty fast when its a no-op and will ensure that on database updates, things just don't blow up
=> always migrate

lib/brains/management/commands/braintree_config.py, lib/brains/tests/test_management.py, requirements/prod.txt
* cope with billing_day_of_month and trial_period, which surprised me last week as being an issue
* dependent upon mozilla/payments-config#14
* fixes #533
=> cope with one off configuration

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/models.py, lib/brains/tests/test_forms.py, lib/brains/tests/test_models.py, lib/brains/tests/test_sale.py, lib/brains/tests/test_webhook.py, lib/brains/urls.py, lib/brains/views/sale.py, lib/brains/views/subscription.py, lib/brains/webhooks.py, lib/buyers/models.py, migrations/59-buyer-optional.sql, solitude/related_fields.py, solitude/settings/base.py
=> add in transaction.sale api

lib/brains/forms.py, lib/brains/tests/base.py, lib/brains/tests/test_forms.py, lib/brains/tests/test_sale.py, lib/brains/tests/test_subscription.py, requirements/prod.txt
* fixes #537
* also check the product is not recurring
* ended up rabbit holing on how to mock out product config
* could not get the mock to stick with the import at the top, which was frustrating
=> check the product config before some transaction.sale action

lib/brains/forms.py, lib/brains/tests/base.py, lib/brains/tests/test_forms.py
This wasn't checking configured product amounts correctly.
=> Allow variable amounts for donations (bug fix)

docs/topics/braintree.rst, lib/brains/forms.py, lib/brains/models.py, lib/brains/tests/base.py, lib/brains/tests/test_forms.py, lib/brains/tests/test_subscription.py, lib/brains/views/subscription.py, migrations/61-bt-subsription-amount.sql
Fixes https://github.com/mozilla/solitude/issues/546
=> Allow custom amount on braintree subscriptions (#546)

lib/brains/management/commands/braintree_config.py, lib/brains/tests/base.py, lib/brains/tests/test_management.py, requirements/prod.txt
This was needed for https://github.com/mozilla/payments-ui/issues/368
=> Configure recurring donations

.baked, docs/topics/generic.rst, lib/brains/forms.py, lib/brains/management/commands/braintree_config.py, lib/brains/management/commands/braintree_webhook.py, lib/brains/tests/test_forms.py, lib/buyers/field.py, lib/buyers/models.py, lib/buyers/tests/test_api.py, lib/buyers/tests/test_models.py, lib/buyers/views.py, lib/transactions/models.py, migrations/63-buyer-email-hash.sql, migrations/64-populate-email-hash.py, solitude/settings/test.py
supports mozilla/payments-service#151
=> add in an email hash
